#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

if ! echo "$COMMIT_MSG" | grep -qE '^(feat|fix|chore|refactor|wip|sync|update|ci)(\([a-zA-Z0-9_-]+\))?: .+'; then
    echo "Error: Commit message does not follow the standard convention."
    exit 1
fi

exit 0