#!/bin/bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
PROHIBITED_BRANCHES=("dev-master" "dev-staging" "development" "master" "main")

for prohibited_branch in "${PROHIBITED_BRANCHES[@]}"; do
    if [[ "$BRANCH_NAME" == "$prohibited_branch" ]]; then
        echo "Error: Committing directly to '$BRANCH_NAME' is not allowed, Please create a new branch for your changes."
        exit 1
    fi
done

exit 0
